[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

[lib]
name = "tetris"
path = "src/lib.rs"

[[bin]]
name = "tetris"
path = "src/main.rs"

[dependencies]
crossterm = "0.27"
rand = "0.8"
ratatui = "0.26"

[dev-dependencies]
serial_test = "3.0"
